# 0 Vectors and Matrices: NumPy

First, let's review some mathematical concepts:
- A *scalar* is single number.
- A *vector* is a one-dimensional array of numbers.
- A *matrix* is a two-dimensional collection or array of numbers, with size $n \times m$.

$X = x_{ij} = \begin{bmatrix}
    X_{11} & X_{12} & \ldots & X_{1m} \\
    X_{21} & X_{22} & \ldots & X_{2m} \\
    \vdots & \vdots & \ddots & \vdots \\
    X_{n1} & X_{n2} & \ldots & X_{nm}
  \end{bmatrix}$

where the indices:  
$i = 1, \ldots, n$  (number of rows)  
$j = 1, \ldots, m$  (number of columns)

### Matrix types

There are many types of matrices:
- *Row vector:* size $1 \times m$.
- *Column vector:* size $n \times 1$.
- *Square matrix:* when $n = m$.
- *Zero matrix:* when $x_{ij} = 0$.
- *Symmetric matrix:* when $x_{ij} = x_{ji}$.
- *Diagonal matrix:* a square matrix which has non-zero elements on the leading diagonal and zeros everywhere else.
- *Identity matrix:* a diagonal matrix with 1 in all places of the leading diagonal. Usually named $I$.

The best way to perform matrix calculations in Python is with the package `numpy`.

Further reading:
- [Numpy homepage](http://www.numpy.org)
- [Numpy tutorial](https://numpy.org/doc/stable/user/quickstart.html)

# 1. Numpy Intro
NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

The NumPy library contains multidimensional array and matrix data structures (you’ll find more information about this in later sections). It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

In [99]:
import numpy as np
print("This is the Numpy version: " + np.__version__)

This is the Numpy version: 2.3.3


# 2. Create arrays

There are 6 general mechanisms for creating arrays:

    Conversion from other Python structures (i.e. lists and tuples)

    Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

    Replicating, joining, or mutating existing arrays

    Reading arrays from disk, either from standard or custom formats

    Creating arrays from raw bytes through the use of strings or buffers

    Use of special library functions (e.g., random)


## 2.1 Using Python sequences such as lists and tuples
Lists and tuples are defined using [...] and (...), respectively. Lists and tuples can define ndarray creation:

 * a list of numbers will create a 1D array,

 * a list of lists will create a 2D array,

 * further nested lists will create higher-dimensional arrays. In general, any array object is called an ndarray in NumPy.


In [100]:
import numpy as np

a1D = np.array([1, 2, 3, 4])

a2D = np.array([[1, 2], [3, 4]])

a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [101]:
a1D

array([1, 2, 3, 4])

In [102]:
a2D

array([[1, 2],
       [3, 4]])

In [103]:
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# 2.2 Intrinsic NumPy array creation functions
NumPy has over 40 built-in functions for creating arrays.    
<https://numpy.org/doc/stable/reference/routines.array-creation.html#routines-array-creation>

These functions can be split into roughly three categories, based on the dimension of the array they create:

    1D arrays
    2D arrays
    ndarrays


### 2.2.1 1D array creation functions
 numpy.linspace and numpy.arange generally need at least two inputs, start and stop

In [104]:
#np.arrange creates arrays with regularly incrementing values
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [105]:
np.arange(2, 15, dtype=float)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.])

In [106]:
np.arange(2, 4, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
       3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9])

In [107]:
#np.linspace create arrays with a specified number of elements, and spaced equally between
#the specified beginning and end values
np.linspace(1, 10, 7)
#The advantage of this creation function is that you guarantee the number of elements
# and the starting and end point. The previous arange(start, stop, step) will not include the value stop.

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

### 2.2.2 2D array creation functions
numpy.eye, numpy.diag, and numpy.vander define properties of special matrices represented as 2D arrays.


np.eye(n, m) defines a 2D identity matrix. The elements where i=j (row index and column index are equal) are 1 and the rest are 0

In [108]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [109]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

numpy.diag can define either a square 2D array with given values along the diagonal or if given a 2D array returns a 1D array that is only the diagonal elements.

In [110]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [111]:
# [1,2,3] son los elementos de la diagonal
# 2 número de posiciones respecto a la diagonal principal(+: arriba;-:abajo)
np.diag([1, 2, 3],2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [112]:
a = np.array([[1, 2], [3, 4]])
# extrae la diagonal principal de una matriz
np.diag(a)

array([1, 4])

vander(x, n) defines a Vandermonde matrix as a 2D NumPy array. Each column of the Vandermonde matrix is a decreasing power of the input 1D array or list or tuple, x where the highest polynomial order is n-1.

In [113]:
# 2: numero de columnas
# genera columnas con potencias del vector np.linspace(0,2,5): array([0. , 0.5, 1. , 1.5, 2. ])
# primera Col: potencia elevado a 1
# segunda Col: potencia elevado a 0
np.vander(np.linspace(0, 2, 5), 2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [114]:
np.vander([1, 2, 3, 4], 2)

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [115]:
np.vander((1, 2, 3, 4), 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

### 2.2.3 ND array creation functions

The ndarray creation functions e.g. numpy.ones, numpy.zeros, and random define arrays based upon the desired shape.

numpy.zeros will create an array filled with 0 values with the specified shape.

In [116]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [117]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

numpy.ones will create an array filled with 1 values. It is identical to zeros

In [118]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

The random method of the result of default_rng will create an array filled with random values between 0 and 1. It is included with the numpy.random library.

In [119]:
#The seed is set to 42 so you can reproduce these pseudorandom numbers:

np.random.default_rng(42).random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

np.indeces will create a set of arrays (stacked as a one-higher dimensioned array), one per dimension with each representing variation in that dimension

In [120]:
# Genera un array que contiene los índices de una cuadrícula multidimensional (en este caso de 3x3).
# La primera matriz representa los índices de las filas.
# La segunda matriz representa los índices de las columnas.
np.indices((3, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

### 2.2.4 Replicating, joining, or mutating existing arrays
Once you have created arrays, you can replicate, join, or mutate those existing arrays to create new arrays. When you assign an array or its elements to a new variable, you have to explicitly numpy.copy the array, otherwise the variable is a view into the original array.

In [121]:
a = np.array([1, 2, 3, 4, 5, 6])

# b comparte la misma posicion de memoria que a (2 primeros elementos)
b = a[:2]

# b se modifica y consecuentemente también a
b += 1

print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In this example, you did not create a new array. You created a variable, b that viewed the first 2 elements of a. When you added 1 to b you would get the same result by adding 1 to a[:2]. If you want to create a new array, use the numpy.copy array creation routine as such:

In [122]:
a = np.array([1, 2, 3, 4])

b = a[:2].copy()

b += 1

print('a = ', a, 'b = ', b)

a =  [1 2 3 4] b =  [2 3]


There are a number of routines to join existing arrays e.g. numpy.vstack, numpy.hstack, and numpy.block. Here is an example of joining four 2-by-2 arrays into a 4-by-4 array using block:

In [123]:
A = np.ones((2, 2))
print(f"A={A}")
B = np.eye(2, 2)
print(f"B= {B}")
C = np.zeros((2, 2))
print(f"C= {C}")
D = np.diag((-3, -4))
print(f"D= {D}")

np.block([[A, B], [C, D]])

A=[[1. 1.]
 [1. 1.]]
B= [[1. 0.]
 [0. 1.]]
C= [[0. 0.]
 [0. 0.]]
D= [[-3  0]
 [ 0 -4]]


array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

# 3. Indexing

## 3.1 Basic indexing

In [124]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
x[2]

np.int64(2)

In [126]:
# -1 es el ultimo valor
x[-2]

np.int64(8)

In [127]:
# cambio las dimensiones a 2 filas por 5 columnas
x.shape=(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [128]:
x[1, 3]
8

8

In [129]:
x[1, -1]

np.int64(9)

In [130]:
x[0]

array([0, 1, 2, 3, 4])

In [131]:
x[0][3]

np.int64(3)

## 3.2 Slicing

In [132]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:

x[1:7]

array([1, 2, 3, 4, 5, 6])

In [134]:
x[1:7:2]

array([1, 3, 5])

In [135]:
x[-2:10]

array([8, 9])

In [136]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [137]:
x[5:]

array([5, 6, 7, 8, 9])

In [138]:
x[:5]

array([0, 1, 2, 3, 4])

# 4 Some Funcs

In [139]:
import numpy as np

v = np.array([2.1,3.2,4.3])

v

array([2.1, 3.2, 4.3])

In [140]:
# numero de dimensiones
v.ndim

1

In [141]:
# 1)Si unidimensional muestra los elementos
v.shape

(3,)

In [142]:
# 2) si bidimensional filas x columnas
a2D = np.array([[1, 2], [3, 4]])
a2D.shape

(2, 2)

In [143]:
# tipo de datos
v.dtype.name
# podemos mezclar datos
# mixed_array = np.array([1, 'a', 3.14], dtype=object)

'float64'

In [144]:
# numero elementos del array
print(v.size)
print(a2D.size)


3
4


In [145]:
v.itemsize #Length of one array element in bytes

8

# 5. Summary

In [146]:
x = np.linspace(0, 3*np.pi, 100)
print("Size: "+str(len(x)))
print(x)

Size: 100
[0.         0.09519978 0.19039955 0.28559933 0.38079911 0.47599889
 0.57119866 0.66639844 0.76159822 0.856798   0.95199777 1.04719755
 1.14239733 1.23759711 1.33279688 1.42799666 1.52319644 1.61839622
 1.71359599 1.80879577 1.90399555 1.99919533 2.0943951  2.18959488
 2.28479466 2.37999443 2.47519421 2.57039399 2.66559377 2.76079354
 2.85599332 2.9511931  3.04639288 3.14159265 3.23679243 3.33199221
 3.42719199 3.52239176 3.61759154 3.71279132 3.8079911  3.90319087
 3.99839065 4.09359043 4.1887902  4.28398998 4.37918976 4.47438954
 4.56958931 4.66478909 4.75998887 4.85518865 4.95038842 5.0455882
 5.14078798 5.23598776 5.33118753 5.42638731 5.52158709 5.61678687
 5.71198664 5.80718642 5.9023862  5.99758598 6.09278575 6.18798553
 6.28318531 6.37838508 6.47358486 6.56878464 6.66398442 6.75918419
 6.85438397 6.94958375 7.04478353 7.1399833  7.23518308 7.33038286
 7.42558264 7.52078241 7.61598219 7.71118197 7.80638175 7.90158152
 7.9967813  8.09198108 8.18718085 8.28238063 8.377580

In [147]:
# Why we retrieve an error?
import math



In [148]:
y=np.sin(x)
y

array([ 0.00000000e+00,  9.50560433e-02,  1.89251244e-01,  2.81732557e-01,
        3.71662456e-01,  4.58226522e-01,  5.40640817e-01,  6.18158986e-01,
        6.90079011e-01,  7.55749574e-01,  8.14575952e-01,  8.66025404e-01,
        9.09631995e-01,  9.45000819e-01,  9.71811568e-01,  9.89821442e-01,
        9.98867339e-01,  9.98867339e-01,  9.89821442e-01,  9.71811568e-01,
        9.45000819e-01,  9.09631995e-01,  8.66025404e-01,  8.14575952e-01,
        7.55749574e-01,  6.90079011e-01,  6.18158986e-01,  5.40640817e-01,
        4.58226522e-01,  3.71662456e-01,  2.81732557e-01,  1.89251244e-01,
        9.50560433e-02,  1.22464680e-16, -9.50560433e-02, -1.89251244e-01,
       -2.81732557e-01, -3.71662456e-01, -4.58226522e-01, -5.40640817e-01,
       -6.18158986e-01, -6.90079011e-01, -7.55749574e-01, -8.14575952e-01,
       -8.66025404e-01, -9.09631995e-01, -9.45000819e-01, -9.71811568e-01,
       -9.89821442e-01, -9.98867339e-01, -9.98867339e-01, -9.89821442e-01,
       -9.71811568e-01, -

# 6. Matrix

---
## 6.1 Create matrices

Create a matrix.

In [149]:
X = np.matrix([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

X

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [150]:
X.ndim

2

In [151]:
X.shape

(3, 3)

In [152]:
X.dtype.name

'int64'

In [153]:
X.size

9

In [154]:
#Longitud en bytes
X.itemsize

8

Create 5x4 zero matrix

In [155]:
shape = (5, 4)
M = np.zeros(shape)
M

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Create 2x3 matrix, every element set to 7.

In [156]:
shape = (2, 3)
M = np.ones(shape)
M = 7 * M
M

array([[7., 7., 7.],
       [7., 7., 7.]])

Create a 3x3 diagonal matrix.

In [157]:
M = np.eye(3)
M

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---
## 6.2 Transposition

The transpose of a matrix is another matrix where rows and column have been swapped.

$ \big[ x_{ij} \big] ^T = x_{ji} $

In [158]:
X.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

---
## 6.3 Reshaping

Reshape matrix and re-arrange elements accordingly. A dimension may be omitted and replaced by `-1`, which means *whatever needed*.

In [159]:
v = np.arange(0, 30)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [160]:
v.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [161]:
# -1 indica que se recalcule el num columnas, con 6 filas
v.reshape(6, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

---
## 6.4 Stacking

Concatenate matrices horizontally or vertically.

In [162]:
shape = (2, 2)
A = np.zeros(shape)
B = np.ones(shape)

In [163]:
items = [A, B]
np.vstack(items)

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [164]:
items = [A, B]
np.hstack(items)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

---
## 6.5 Evaluate conditions

Evaluate conditional sentences element-wise with `where(condition, output_true, ouput_false)`

In [165]:
M = np.arange(0, 30).reshape(5, -1)
M

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [166]:
N = np.where(M < 15, 0, 42)
N

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 42, 42, 42],
       [42, 42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42, 42]])

---
## 6.6 Submatrix

Submatrices are calculated by indexing specific sections of the original matrix.  

The slice operator `:` comes in handy. Remember indices in Python start at `0`.  

The example below should be read as:  
*retrieve row with index* `2`*, columns starting at index* `1` *(inclusive) until* `3` *(exclusive)*

In [167]:
X[2, 1:3]

matrix([[8, 9]])

---
## 6.7 Matrix addition

Let $A = a_{ij}$ and $B=b_{ij}$ two matrices of the same order, then matrix addition is defined as:  

$C = A+B$  

More specifically:  
$c_{ij} = a_{ij} + b_{ij}$  

Substraction is defined by replacing `+` and `-`.

In [168]:
A = np.matrix([[1, 2],
               [3, 4]])

B = np.matrix([[5, 6],
               [7, 8]])

C = A + B
C

matrix([[ 6,  8],
        [10, 12]])


## 6.8 Scalar multiplication

Let $X = x_{ij}$ then scalar multiplication is defined as:  

$\lambda X = \big[ \lambda x_{ij} \big] $  


In [169]:
2.0 * X

matrix([[ 2.,  4.,  6.],
        [ 8., 10., 12.],
        [14., 16., 18.]])

---
## 6.9 Matrix multiplication

Let $A = a_{ij}$ (N x P) and $B=b_{ij}$ (P x M) two matrices, then matrix multiplication is defined as:  

$C = A \times B$  

More specifically:  
$\begin{align}
c_{ij} = \sum_{k=1}^{P} a_{ik} b_{kj}
\end{align}$

Matrices cannot be divided by one another. Multiply by the inverse instead.

In [170]:
A = np.matrix([[1, 1, 1],
               [2, 2, 2]])

B = np.matrix([[3, 4],
               [3, 4],
               [3, 4]])

C = A @ B
C

matrix([[ 9, 12],
        [18, 24]])

---
## 6.10 Rank of a matrix

The *rank* is given by the maximum number of linearly independent rows or columns contained in the matrix.  
If the rank is equal to the matrix dimension, then it is a *matrix of full rank*. Otherwise, it is a *short rank matrix* or *singular matrix*.

In [171]:
from numpy.linalg import matrix_rank

X = np.matrix([[1, 2, 3],
               [0, 1, 0],
               [2, 4, 6]])

# short rank matrix, first and third rows are linearly dependent
matrix_rank(X)

np.int64(2)

---
## 6.11 Matrix inverse

Let $X = x_{ij}$ a square matrix, then $X^{-1}$ is its inverse and must satisfy:  

$X \times X^{-1} = X^{-1} \times X = I$  

Being $I$ the identity matrix.

It is calculated this way:

$\begin{align}X^{-1} = \frac{1}{\left| X \right|} \big( \text{adj} \, A \big)
\end{align}$

In [172]:
from numpy.linalg import inv

X = np.matrix([[1, 2],
               [3, 4]])

inverse = inv(X)
inverse

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

Quick test, the operation below returns the identity matrix.

In [173]:
inverse @ X

matrix([[1.00000000e+00, 0.00000000e+00],
        [1.11022302e-16, 1.00000000e+00]])

---
## 6.12 Matrix determinant

The expression $\left| X \right|$ seen above, refers to a scalar known as the *determinant* of the matrix.  
If it is equal to zero, then the matrix is singular. Consequently, only matrices of full rank may be inversed.

In [174]:
from numpy.linalg import det

det(X)

np.float64(-2.0000000000000004)

---
## 6.13 Trace of a matrix

The *trace* of a square matrix is the sum of the elements on its leading diagonal.

$\begin{align}
Tr(X) = \sum_{i=1}^{N} x_{ii}
\end{align}
$

In [175]:
X.trace()

matrix([[5]])

---
## 6.14. The eigenvalues and eigenvectors of a matrix

An *eigenvector* or *characteristic vector* of a linear transformation $M$ is a non-zero vector $v$ that changes by only a scalar factor $\lambda$ when that linear transformation is applied to it.  

Let $M$ denote a $p \times p$ matrix and $v$ a $p \times 1$ column vector.  

$\begin{align}
M v = \lambda I v
\end{align}$

Which is equivalent to:

$\begin{align}
\left( M - \lambda I \right) v = 0
\end{align}$

Seeing that $v \neq 0$ by definition, this system of equations will have a non-zero solution for $v$ if:

$\begin{align}
\left| M - \lambda I \right| = 0
\end{align}$

This is called the *characteristic equation* and its roots are the *eigenvalues* of the matrix, which have the following properties:
- The number of eigenvalues is the rank of the matrix.
- The product of the eigenvalues is the determinant.
- The sum of the eigenvalues is the trace.


In [176]:
import numpy as np
from numpy.linalg import eig, eigvals

M = np.matrix([[2, 1, 0],
               [1, 2, 0],
               [0, 0, 1]])

eigenvalues = eigvals(M)

In [177]:
eigenvalues

array([3., 1., 1.])

*Eigenvectors* may be obtained as well with function `eig()` that returns both eigenvalues and eigenvectors.

In [178]:
result = eig(M)
eigenvalues = result[0]
eigenvectors = result[1]

eigenvectors

matrix([[ 0.70710678, -0.70710678,  0.        ],
        [ 0.70710678,  0.70710678,  0.        ],
        [ 0.        ,  0.        ,  1.        ]])

Let's see what happens when each eigenvector is multiplied by the matrix $M$:  

$\begin{align}M v = \lambda v \end{align}$

In [179]:
n = len(eigenvalues)

for i in range(n):
    v = eigenvectors[i]
    mv = M @ v.T

    print(f'[{i}]')
    print(f'\t    v = {v}')
    print(f'\tM x v = {mv.T}')

[0]
	    v = [[ 0.70710678 -0.70710678  0.        ]]
	M x v = [[ 0.70710678 -0.70710678  0.        ]]
[1]
	    v = [[0.70710678 0.70710678 0.        ]]
	M x v = [[2.12132034 2.12132034 0.        ]]
[2]
	    v = [[0. 0. 1.]]
	M x v = [[0. 0. 1.]]


And this property only applies to eigenvectors: a randomly chosen vector will not show this behavior.

In [180]:
v = np.matrix([[1., 2., 3.]])
mv = M @ v.T

print(f'\t    v = {v}')
print(f'\tM x v = {mv.T}')

	    v = [[1. 2. 3.]]
	M x v = [[4. 5. 3.]]


# Referencias:     
<https://aprendeconalf.es/docencia/python/manual/numpy/>