In [ ]:
import numpy as np


# Ejercicio 1

Crea un array con los números del 1 al 10 y muestra su tipo de dato y su forma (shape).

In [15]:
arr_incremento = np.arange(1, 10, 1)

print("Arr", arr_incremento)
print("Tipo de dato", arr_incremento.dtype)
print("Forma ", arr_incremento.shape)

Arr [1 2 3 4 5 6 7 8 9]
Tipo de dato int64
Forma  (9,)


# Ejercicio 2

Dados los arrays a = [1,2,3,4,5] y b = [10,20,30,40,50]:
- Calcula la suma de ambos arrays
- Calcula el producto elemento a elemento
- Calcula el promedio del array b

In [28]:
a = np.array([1,2,3,4,5]) 
b = np.array([10,20,30,40,50])

print(a + b)
print(a * b)
print(b.mean())

[11 22 33 44 55]
[ 10  40  90 160 250]
30.0


# Ejercicio 3

Crea un array con np.arange(20). Muestra:
- Los primeros 5 elementos
- Los últimos 5 elementos
- Los elementos del 5 al 10

In [32]:
print((np.arange(20))[0:5])
print((np.arange(20))[15:20])
print((np.arange(20))[5:10])

[0 1 2 3 4]
[15 16 17 18 19]
[5 6 7 8 9]


# Ejercicio 4

Define dos matrices A y B de 2x2 con valores del 1 al 8.
Calcula:
- A + B
- A @ B (producto matricial)
- La transpuesta de A

In [39]:
A = np.matrix([[1,2],[3,4]]) 
B = np.matrix([[5,6],[7,8]]) 

print(A + B)
print(A @ B)
print(A.T)

[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


# Ejercicio 5

Genera un array de 10 enteros aleatorios entre 0 y 100.
Muestra:
- El valor máximo y mínimo
- La media y desviación estándar
- El índice del valor máximo

In [43]:

rng = np.random.default_rng(42)
arr = rng.integers(0, 100, 10)
print("Array:", arr)

print("Valor máximo: ", arr.max())
print("Valor mínimo: ", arr.min())
print("Media: ", arr.mean())
print("Desviación estándar: ", arr.std())
print("Índice del valor máximo: ", np.argmax(arr))

Array: [ 8 77 65 43 43 85  8 69 20  9]
Valor máximo:  85
Valor mínimo:  8
Media:  42.7
Desviación estándar:  28.660251220113196
Índice del valor máximo:  5
